global using System.Diagnostics;
global using HackerRank.Console;
global using HackerRank.Console.ChallengeSetups;
global using HackerRank.Console.ChallengeSetups.OneMonthWeekOne;
global using HackerRank.Console.ChallengeSetups.OneMonthWeekTwo;
global using HackerRank.Core;
global using HackerRank.Core.Challenges;
global using HackerRank.Core.Challenges.OneMonthWeekOne;
global using HackerRank.Core.Challenges.OneMonthWeekTwo;
